# Generated by Django 4.2.8 on 2023-12-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(help_text='Game name', max_length=100)),
                ('game_english_name', models.CharField(blank=True, default='', help_text='Game name', max_length=100)),
                ('game_view', models.BooleanField(default=True, help_text='Game on off')),
                ('game_description', models.TextField(blank=True, help_text='Game description')),
                ('game_tag', models.TextField(blank=True, help_text='Game description')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Created Date time')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nickname', models.CharField(help_text='User nickname', max_length=30, unique=True)),
                ('user_password', models.CharField(help_text='User password', max_length=30)),
                ('user_email', models.EmailField(help_text='User E-mail', max_length=254, unique=True)),
                ('user_rermissions', models.CharField(default='normal', help_text='User rermissions', max_length=11)),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Created Date time')),
            ],
        ),
    ]
