# Generated by Django 4.2.8 on 2024-01-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_gold',
            field=models.BigIntegerField(default=1000, help_text='User gold'),
        ),
    ]
