# Generated by Django 3.2.2 on 2023-11-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_auto_20231130_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='game_view',
            field=models.BooleanField(default=True, help_text='Game on off'),
        ),
    ]
