# Generated by Django 3.2.2 on 2023-12-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_gamemodel_game_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='game_english_name',
            field=models.CharField(blank=True, default='', help_text='Game name', max_length=100),
        ),
    ]
