# Generated by Django 3.2.2 on 2023-12-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0004_gamemodel_game_english_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_rermissions',
            field=models.CharField(default='normal', help_text='User rermissions', max_length=11),
        ),
    ]
